name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${organization.name}
website: ${organization.url}

main: com.shepherdjerred.sthorses.Main

commands:
    sth:
        description: Base command
        aliases: [sthorses]
        
permissions:
    stHorses.*:
        description: Gives access to all plugin functions
        children:
            stHorses.reload: true
            stHorses.save: true
            stHorses.store: true
    stHorses.reload:
        description: Gives access to /sth reload
        default: op
    stHorses.spawn:
        description: Allows saving horses to saddles
        default: true
    stHorses.store:
        description: Allows spawning horses from saddles
        default: true